### ISSUE TITLE
目前需要停留在微信界面，考虑支持下后台抢红包？

### ISSUE THREAD

**Issue by pablezhang** [YummyLau/WechatTools#11]
目前需要停留在微信界面，考虑支持下后台抢红包？

**Comment by YummyLau** [comment]
@pablezhang 最新版本开启微信通知栏功能同时开启插件app的通知栏功能，是可以的。

**Comment by pablezhang** [comment]
我使用v1.0.4版本，开启所有通知，该功能不行。
手机：vivoZ1
微信版本：7.0.10
Android: v8.1.0

**Comment by YummyLau** [comment]
如果你的app在后台但是有通知栏支持的话是可以的。确保你有通知栏显示在你的界面。或者可以提供下截图

**Comment by changweining** [comment]
抢到了后就在本群停留，其他群再发红包，他还是不会抢，需要回到首页页面才能继续自动抢。希望改进呀。哈哈哈哈

**Comment by YummyLau** [comment]
@changweining 默认会到当前界面等待的。后续可以改进下。

**Comment by pablezhang** [comment]
> 如果你的app在后台但是有通知栏支持的话是可以的。确保你有通知栏显示在你的界面。或者可以提供下截图

![image](https://user-images.githubusercontent.com/25419312/98090616-39aa9700-1ebf-11eb-9996-bfbb5e2f0a23.png)

在后台还是不能自动跳到微信界面抢红包。

除了上面这条外，其他的问题貌似都修复了。

**Comment by pablezhang** [comment]
> > 如果你的app在后台但是有通知栏支持的话是可以的。确保你有通知栏显示在你的界面。或者可以提供下截图
> 
> ![image](https://user-images.githubusercontent.com/25419312/98090616-39aa9700-1ebf-11eb-9996-bfbb5e2f0a23.png)
> 
> 在后台还是不能自动跳到微信界面抢红包。
> 
> 除了上面这条外，其他的问题貌似都修复了。

我关闭“支持通知栏抢红”后，再次开启“只是通知栏抢红包”就该功能又可以使用了，感谢~

**Comment by YummyLau** [comment]
暂时没有太多时间新增功能。
