### ISSUE TITLE
是否可以考虑设置过滤某些群的红包

### ISSUE THREAD

**Issue by kwu130** [YummyLau/WechatTools#2]

**Comment by kwu130** [comment]
有些群可能是平时屏蔽掉的，不参与聊天的，希望可以增加过滤某些群的红包的功能。

**Comment by kwu130** [comment]
我测试了一下，需要保持在微信界面才能识别红包，并抢红包，能否实现在任意界面，当通知栏收到微信红包的提示直接定位到相应微信群进行抢红包呀？

**Comment by YummyLau** [comment]
@kwu130 过滤某些群可以做到，通知栏也应该是，不过国产rom很多，交融可能是一个问题。   基于accessibility 实现的，理论上能拿到window界面变化的都可以。 有时间会考虑更新下。

**Comment by YummyLau** [comment]
@kwu130 @kwu130 过滤某些群可以做到（但需要用户输入配置），通知栏也应该是，不过国产rom很多，兼容可能是一个问题。 基于accessibility 实现的，理论上能拿到window界面变化的都可以。 有时间会考虑更新下。

**Comment by kwu130** [comment]
> @kwu130 @kwu130 过滤某些群可以做到（但需要用户输入配置），通知栏也应该是，不过国产rom很多，兼容可能是一个问题。 基于accessibility 实现的，理论上能拿到window界面变化的都可以。 有时间会考虑更新下。

好的，等你更新。

**Comment by YummyLau** [comment]
1.0.2版本，支持悬浮窗，过滤回话。通知栏需要适配rom，目前抽不出太多时间开发，都是空闲的时候搞搞... @kwu130
