### ISSUE TITLE
7.0.10 报persuit_of_720

### ISSUE THREAD

**Issue by morysky** [YummyLau/WechatTools#3]
如题。老哥尽快修复？

**Comment by YummyLau** [comment]
> 如题。老哥尽快修复？

你指的是提示“读取微信版本失败, 请联系开发人员！ (WeChat: pursuit_of_720)”吗？
麻烦提供下手机的机型版本，微信是否安装，微信版本，是否双开等信息。

**Comment by morysky** [comment]
> > 如题。老哥尽快修复？
> 
> 你指的是提示“读取微信版本失败, 请联系开发人员！ (WeChat: pursuit_of_720)”吗？
> 麻烦提供下手机的机型版本，微信是否安装，微信版本，是否双开等信息。

我这边是小米9，微信版本7.0.10，双开了。
我感觉是双开的锅。

**Comment by morysky** [comment]
> > > 如题。老哥尽快修复？
> > 
> > 
> > 你指的是提示“读取微信版本失败, 请联系开发人员！ (WeChat: pursuit_of_720)”吗？
> > 麻烦提供下手机的机型版本，微信是否安装，微信版本，是否双开等信息。
> 
> 我这边是小米9，微信版本7.0.10，双开了。
> 我感觉是双开的锅。

我把双开关了。似乎也不行。

**Comment by morysky** [comment]
老哥，我这边可能装的是当时内测版的7.0.10，跟这个有关么？其他上下问信息应该没有了。

**Comment by YummyLau** [comment]
@morysky 双开可能会有影响，这部分并没有完全测试。  你可以下载个新版版的7.0.10看看。或者直接官网下载，不排除小米渠道的包和官方包不一致。另外1.0.2已经发了，用新版吧

**Comment by morysky** [comment]
三大问题我都排除拉：
1. 双开。已经关了，上次尝试就关啦。
2. 微信版本。之前是从别的同事那里拿到的7.0.10内测版，后来按你的说法从官网下了个APK(build version 1580)，特意避免从小米渠道下载~
3. 下载了最新的1.0.2，还是报错。看来春节薅羊毛悬啦。

**Comment by YummyLau** [comment]
@morysky 不能忍受。加我微信下。 pursuit_of_720 ,然后把机型还有版本，相关情况告知下我，我找个测试机帮你看看。

**Comment by morysky** [comment]
好哒。那wechat沟通吧。issue关啦。
