### ISSUE TITLE
小米MIX2S必须要打开微信才可以抢红包

### ISSUE THREAD

**Issue by soldierm** [YummyLau/WechatTools#7]
设备：小米Mix2s
安卓版本：9
MIUI版本：11.0.2
APP版本：1.0.2
微信版本：7.0.10
问题：必须要打开微信才能抢红包，无论是否开启了抢红包APP悬浮窗，只要微信切到了后台就无法抢

**Comment by soldierm** [comment]
如果锁屏了，也无法抢红包

**Comment by StellaSong12** [comment]
当前版本v1.0.2仅支持停留在微信首页或聊天页抢红包，如有其它功能需求，欢迎提issue或pull req

**Comment by YummyLau** [comment]
@soldierm 这个只是基于accessibility做的啦，锁屏还没有支持，这个要后续支持通知栏功能才可以。

**Comment by YummyLau** [comment]
@minglinpop  1.0.3已发布支持
